#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

mstm/Allwclean

wcleanLnIncludeAll SOFC

wclean SOFC

# ----------------------------------------------------------------- end-of-file
