#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wcleanLnIncludeAll stefanTube
wcleanLnIncludeAll sofcFoam

wclean stefanTube
wclean sofcFoam

# ----------------------------------------------------------------- end-of-file
