#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

# cleaning solvers 

wclean all solvers
wclean all libraries
wclean all utilities

# purge option to clean executables
if [ "$1" = "--purge" ]
then
    # clean solver executables
    rm -f $FOAM_USER_APPBIN/transFoam

fi
