#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

thermophysicalModels/Allwmake

wmake libso diffusivityModels
wmake libso momentumTransport
wmake libso multiSpeciesTransportModels

# ----------------------------------------------------------------- end-of-file
