#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmakeLnInclude specie

wmake libso SOFCteamFunctions
wmake libso reactionThermo
wmake libso materials

# ----------------------------------------------------------------- end-of-file
